export const SET_REPOSITORIES = 'SET_REPOSITORIES';
export const FETCH_REPOSITORIES_FAILED = 'FETCH_REPOSITORIES_FAILED';

export const SET_REPOSITORY = 'SET_REPOSITORY';
export const FETCH_REPOSITORY_FAILED = 'FETCH_REPOSITORY_FAILED';

export const SET_ISSUES = 'SET_ISSUES';
export const FETCH_ISSUES_FAILED = 'FETCH_ISSUES_FAILED';

export const SET_PULLREQUESTS = 'SET_PULLREQUESTS';
export const FETCH_PULLREQUESTS_FAILED = 'FETCH_PULLREQUESTS_FAILED';